<a href="https://colab.research.google.com/github/tandat-1305/Data-Analysis-with-Python/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#a[r,c]
a[1,5]

13

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
# ALL 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#All other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [ ]:
# Random số thập phân
np.random.random_sample(a.shape)

array([[0.33359743, 0.94362901, 0.83591222, 0.39958451, 0.64463473,
        0.32363803, 0.01024267],
       [0.00854792, 0.92464039, 0.33574367, 0.73753625, 0.450554  ,
        0.01303506, 0.00952379]])

In [ ]:
np.random.rand(3,3)

array([[0.83778097, 0.71084783, 0.18788359],
       [0.10046291, 0.3322977 , 0.31187768],
       [0.85678324, 0.69574603, 0.01642313]])

In [ ]:
# Random số nguyên
np.random.randint(7,size=(3,3))
# Random 0->7 , matrix 3x3

array([[3, 3, 0],
       [4, 6, 3],
       [1, 2, 1]])

In [ ]:
np.random.randint(-3,7,size=(3,3))
#random -3->7 , matrix 3x3

array([[-1, -3, -3],
       [ 5,  1,  3],
       [ 1, -3, -3]])

In [ ]:
 # Ma trận đơn vị
 np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array 
arr = np.array([[1,2,3]])
arr2 = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr2,3,axis=0)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 1 1 2 2 2 3 3 3]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
 output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5
print(z)

output[1:-1, 1:-1] = z
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [ ]:
a = np.ones((2,3))
print(a)  

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6



1.  Axis = 0 -> tính theo cột

2.  Axis = 1 -> tính theo hàng




In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [ ]:
np.sum(stats, axis=1)

array([ 6, 15])

In [ ]:
a = np.array(([1, 2, 3, 4,], 
              [6, 7, 8, 9,]))
b = np.max(a, axis=1).sum()
b

13

**Reorganizing Array**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#chia 8 dòng 1 cột
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
#Vertically stacking vectors
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.vstack([arr1,arr2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.column_stack(([1,2,3],[4,5,6])) 


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.hstack(([1,2,3],
           [4,5,6])) 

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack(([[1],[2],[3]],[[4],[5],[6]])) 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,4))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

**Miscellaneous**

load data from file

In [ ]:
f = np.genfromtxt('data.txt', delimiter=',')
f = f.astype('int32')
f

array([[ 1,  2,  3,  4,  1,  5,  6,  1,  2,  3,  4,  6,  2,  2],
       [ 1,  2,  3,  4,  6,  5,  6,  1,  2,  3,  4,  6,  2,  2],
       [ 3,  4,  1,  5,  6,  1,  2,  3,  4,  1,  5,  6,  1, 10]],
      dtype=int32)

Boolean Masking and Advanced Indexing


In [ ]:
f > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False]])

In [ ]:
f[f>5]

array([ 6,  6,  6,  6,  6,  6,  6, 10], dtype=int32)

In [ ]:
((f >4) & (f < 8))

array([[False, False, False, False, False,  True,  True, False, False,
        False, False,  True, False, False],
       [False, False, False, False,  True,  True,  True, False, False,
        False, False,  True, False, False],
       [False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False, False]])