<a href="https://colab.research.google.com/github/tandat-1305/Data-Analysis-with-Python/blob/main/Numpy/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
# ALL 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#All other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [ ]:
# Random số thập phân
np.random.random_sample(a.shape)

array([[0.74688237, 0.06077951, 0.44739824, 0.16315015, 0.81084284,
        0.5394877 , 0.95310419],
       [0.2663085 , 0.86595719, 0.49770446, 0.46958524, 0.11939289,
        0.77151479, 0.00154923]])

In [ ]:
np.random.rand(3,3)

array([[0.91866701, 0.99306289, 0.64187112],
       [0.32603613, 0.68104313, 0.26656969],
       [0.82587477, 0.92533945, 0.25699238]])

In [ ]:
# Random số nguyên
np.random.randint(7,size=(3,3))
# Random 0->7 , matrix 3x3

array([[1, 5, 5],
       [6, 6, 3],
       [1, 0, 3]])

In [ ]:
np.random.randint(-3,7,size=(3,3))
#random -3->7 , matrix 3x3

array([[ 1,  3,  1],
       [-2, -3,  6],
       [ 2,  1,  5]])

In [ ]:
 # Ma trận đơn vị
 np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array 
arr = np.array([[1,2,3]])
arr2 = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr2,3,axis=0)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 1 1 2 2 2 3 3 3]
