<a href="https://colab.research.google.com/github/tandat-1305/Data-Analysis-with-Python/blob/main/Numpy/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#a[r,c]
a[1,5]

13

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])